from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(path: str, old: str, new: str) -> None:
    target = ROOT / path
    text = target.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{path}: expected exactly one anchor, found {count}")
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


def patch_query_pipeline() -> None:
    replace_once(
        "core/query_pipeline.py",
        "import math\n",
        "import hashlib\nimport json\nimport math\nimport os\n",
    )
    replace_once(
        "core/query_pipeline.py",
        "from core.l3_graph import get_l3_graph\n",
        "from core.embedding import get_embedder\nfrom core.l3_graph import get_l3_graph\n",
    )
    replace_once(
        "core/query_pipeline.py",
        '''_QUERY_POLICY = "canonical_read_only"\n''',
        '''_QUERY_POLICY = "canonical_read_only"\n_GRANT_PROFILE_ENV = "VELANTRIM_RELEASE_PROFILE"\n_GRANT_PROFILE = "grant"\n_GRANT_EMBEDDER_REASON = "grant_profile_requires_pinned_embedder"\n_EMBEDDER_MISMATCH_FALLBACK = "embedder_mismatch_lexical_fallback"\n_EMBEDDER_PROVIDER_FALLBACK = "embedder_provider_unavailable_lexical_fallback"\n\n\ndef _grant_profile_enabled() -> bool:\n    return os.environ.get(_GRANT_PROFILE_ENV, "").strip().casefold() == _GRANT_PROFILE\n\n\ndef _retrieval_config_id() -> str:\n    payload = json.dumps(\n        get_retrieval_config().to_dict(),\n        sort_keys=True,\n        separators=(",", ":"),\n        ensure_ascii=False,\n    ).encode("utf-8")\n    return hashlib.sha256(payload).hexdigest()\n\n\ndef _mark_legacy_degradation(\n    candidates: List[Dict[str, Any]],\n    *,\n    reason_code: str,\n    active_embedder_id: Optional[str],\n    stored_embedder_id: Optional[str],\n) -> List[Dict[str, Any]]:\n    setattr(candidates, "degradation_reason_code", reason_code)\n    setattr(candidates, "active_embedder_id", active_embedder_id)\n    setattr(candidates, "stored_embedder_id", stored_embedder_id)\n    for rank, item in enumerate(candidates, 1):\n        item["_retrieval_rank"] = rank\n        item["_retrieval_signals"] = ["bounded_legacy_lexical"]\n        item["_active_embedder_id"] = active_embedder_id\n        item["_stored_embedder_id"] = stored_embedder_id\n        item["_retrieval_mode"] = "bounded_legacy_lexical"\n    return candidates\n''',
    )
    replace_once(
        "core/query_pipeline.py",
        '''        return {\n            "mode": "bounded_legacy_lexical",\n            "candidates_examined": examined,\n            "candidate_limit": candidate_limit,\n            "reindex_recommended": True,\n        }\n''',
        '''        metadata: Dict[str, Any] = {\n            "mode": "bounded_legacy_lexical",\n            "candidates_examined": examined,\n            "candidate_limit": candidate_limit,\n            "reindex_recommended": True,\n        }\n        reason_code = getattr(retrieved, "degradation_reason_code", None)\n        if isinstance(reason_code, str) and reason_code:\n            metadata["reason_code"] = reason_code\n        active_id = getattr(retrieved, "active_embedder_id", None)\n        stored_id = getattr(retrieved, "stored_embedder_id", None)\n        if active_id is not None:\n            metadata["active_embedder_id"] = active_id\n        if stored_id is not None:\n            metadata["stored_embedder_id"] = stored_id\n        return metadata\n''',
    )
    old = '''def _resolve_canonical_fact(item: Dict[str, Any]) -> Optional[Dict[str, Any]]:\n    fact_id = item.get("id") or item.get("fact_id")\n    if not isinstance(fact_id, str) or not fact_id:\n        return None\n    node = get_l3_graph().get_fact(fact_id)\n    if node is None:\n        return None\n    snapshot = TrustSnapshot.from_records(\n        fact_id=fact_id,\n        l3=node,\n        l1=get_fact(fact_id),\n        retrieval_score=item.get("_score", item.get("_relevance", 0.0)),\n    )\n    return snapshot.to_fact_dict()\n\n\ndef _retrieve_read_only(query_text: str, k: Optional[int] = None) -> List[Dict[str, Any]]:\n    """Retrieve without creating an embedding-space fingerprint."""\n    limit = get_retrieval_config().k if k is None else k\n    graph = get_l3_graph()\n    if graph.embedder_fingerprint() is not None:\n        return retrieve(query_text, k=limit)\n    return bounded_legacy_retrieve(query_text, k=limit, graph=graph)\n'''
    new = '''def _resolve_canonical_fact(item: Dict[str, Any]) -> Optional[Dict[str, Any]]:\n    fact_id = item.get("id") or item.get("fact_id")\n    if not isinstance(fact_id, str) or not fact_id:\n        return None\n    node = get_l3_graph().get_fact(fact_id)\n    if node is None:\n        return None\n    snapshot = TrustSnapshot.from_records(\n        fact_id=fact_id,\n        l3=node,\n        l1=get_fact(fact_id),\n        retrieval_score=item.get("_score", item.get("_relevance", 0.0)),\n    )\n    fact = snapshot.to_fact_dict()\n    # Retrieval metadata is query-local and never becomes L3/Canon state.\n    for key in (\n        "_retrieval_rank",\n        "_retrieval_signals",\n        "_active_embedder_id",\n        "_stored_embedder_id",\n        "_retrieval_mode",\n        "_graph_explanation",\n    ):\n        if key in item:\n            fact[key] = item[key]\n    return fact\n\n\ndef _retrieve_read_only(query_text: str, k: Optional[int] = None) -> List[Dict[str, Any]]:\n    """Retrieve without silent embedding-space changes or durable mutation."""\n    limit = get_retrieval_config().k if k is None else k\n    graph = get_l3_graph()\n    configured_embedder = os.environ.get("VELANTRIM_EMBEDDER", "auto").strip().casefold() or "auto"\n    if _grant_profile_enabled() and configured_embedder == "auto":\n        raise LegacyRetrievalUnavailable(\n            "grant profile requires an explicit VELANTRIM_EMBEDDER value",\n            reason_code=_GRANT_EMBEDDER_REASON,\n        )\n\n    stored = graph.embedder_fingerprint()\n    if stored is None:\n        candidates = bounded_legacy_retrieve(query_text, k=limit, graph=graph)\n        return _mark_legacy_degradation(\n            candidates,\n            reason_code=LEGACY_REINDEX_REASON_CODE,\n            active_embedder_id=None,\n            stored_embedder_id=None,\n        )\n\n    try:\n        active = get_embedder().id\n    except Exception as exc:\n        candidates = bounded_legacy_retrieve(query_text, k=limit, graph=graph)\n        return _mark_legacy_degradation(\n            candidates,\n            reason_code=_EMBEDDER_PROVIDER_FALLBACK,\n            active_embedder_id=None,\n            stored_embedder_id=stored,\n        )\n\n    if active != stored:\n        candidates = bounded_legacy_retrieve(query_text, k=limit, graph=graph)\n        return _mark_legacy_degradation(\n            candidates,\n            reason_code=_EMBEDDER_MISMATCH_FALLBACK,\n            active_embedder_id=active,\n            stored_embedder_id=stored,\n        )\n\n    retrieved = retrieve(query_text, k=limit)\n    for rank, item in enumerate(retrieved, 1):\n        item.setdefault("_retrieval_rank", rank)\n        item.setdefault("_active_embedder_id", active)\n        item.setdefault("_stored_embedder_id", stored)\n        item.setdefault("_retrieval_mode", "admitted_memory_hybrid")\n    return retrieved\n'''
    replace_once("core/query_pipeline.py", old, new)
    replace_once(
        "core/query_pipeline.py",
        '''    trace_input = [\n        {\n            "id": fact["fact_id"],\n            "source": fact.get("source"),\n            "origin": "canonical_read",\n            "epistemic_state": fact.get("epistemic_state"),\n            "_score": fact.get("_score", 0.0),\n        }\n        for fact in facts\n    ]\n''',
        '''    config_id = _retrieval_config_id()\n    trace_input = [\n        {\n            "id": fact["fact_id"],\n            "source": fact.get("source"),\n            "origin": "canonical_read",\n            "epistemic_state": fact.get("epistemic_state"),\n            "_score": fact.get("_score", 0.0),\n            "_retrieval_rank": fact.get("_retrieval_rank"),\n            "_retrieval_signals": fact.get("_retrieval_signals", []),\n            "_active_embedder_id": fact.get("_active_embedder_id"),\n            "_stored_embedder_id": fact.get("_stored_embedder_id"),\n            "_retrieval_mode": fact.get("_retrieval_mode"),\n            "_retrieval_config_id": config_id,\n            "_projection_id": _QUERY_POLICY,\n            "_graph_explanation": fact.get("_graph_explanation"),\n        }\n        for fact in facts\n    ]\n''',
    )


def patch_trace() -> None:
    start = "def build_trace(retrieved: List[Dict[str, Any]]) -> List[Dict[str, Any]]:\n"
    end = "\n\ndef promote_trace(\n"
    path = ROOT / "core/trace.py"
    text = path.read_text(encoding="utf-8")
    a = text.index(start)
    b = text.index(end, a)
    replacement = '''def _safe_score(value: Any) -> float:\n    if isinstance(value, bool) or not isinstance(value, (int, float)):\n        return 0.0\n    try:\n        score = float(value)\n    except OverflowError:\n        return 0.0\n    return score if score == score and score not in (float("inf"), float("-inf")) else 0.0\n\n\ndef build_trace(retrieved: List[Dict[str, Any]]) -> List[Dict[str, Any]]:\n    """Build TRACE v2: query-local retrieval explanation, never evidence authority."""\n    trace: List[Dict[str, Any]] = []\n    now = datetime.now(timezone.utc).isoformat()\n\n    for fallback_rank, item in enumerate(retrieved, 1):\n        fact_id = item.get("id") or item.get("fact_id")\n        if not fact_id:\n            continue\n        rank = item.get("_retrieval_rank", fallback_rank)\n        if isinstance(rank, bool) or not isinstance(rank, int) or rank < 1:\n            rank = fallback_rank\n        signals = item.get("_retrieval_signals", [])\n        if not isinstance(signals, list):\n            signals = []\n        signals = [signal for signal in signals if isinstance(signal, str) and signal]\n        if not signals:\n            signals = [str(item.get("origin", "retrieval"))]\n\n        entry: Dict[str, Any] = {\n            "trace_version": 2,\n            "fact_id": fact_id,\n            "source": item.get("source", "unknown"),\n            "origin": item.get("origin", "retrieval"),\n            "epistemic_state": item.get("epistemic_state", "Observed"),\n            "retrieval_rank": rank,\n            "retrieval_score": round(_safe_score(item.get("_score", 0.0)), 4),\n            "retrieval_signals": list(dict.fromkeys(signals)),\n            "active_embedder_id": item.get("_active_embedder_id"),\n            "stored_embedder_id": item.get("_stored_embedder_id"),\n            "retrieval_mode": item.get("_retrieval_mode"),\n            "retrieval_config_id": item.get("_retrieval_config_id"),\n            "projection_id": item.get("_projection_id"),\n            "retrieved_at": now,\n        }\n        graph_explanation = item.get("_graph_explanation")\n        if isinstance(graph_explanation, dict):\n            entry["graph_explanation"] = graph_explanation\n        trace.append(entry)\n\n    return trace\n'''
    path.write_text(text[:a] + replacement + text[b:], encoding="utf-8")
    replace_once(
        "core/trace.py",
        '''            f"state={el.get('epistemic_state', '?')} | "\n            f"confidence={el.get('confidence', '?')}"\n''',
        '''            f"state={el.get('epistemic_state', '?')} | "\n            f"retrieval_score={el.get('retrieval_score', '?')}"\n''',
    )


def patch_pipeline_explanation() -> None:
    replace_once(
        "core/pipeline.py",
        '''    current = dict(sorted(\n        current.items(), key=lambda item: (-item[1], item[0])\n    )[:cfg.graph_walk_frontier_limit])\n\n    for _hop in range(cfg.graph_walk_hops):\n        nxt: Dict[str, float] = {}\n''',
        '''    current = dict(sorted(\n        current.items(), key=lambda item: (-item[1], item[0])\n    )[:cfg.graph_walk_frontier_limit])\n    best_path: Dict[str, Dict[str, Any]] = {\n        fid: {\n            "seed_fact_id": fid,\n            "fact_ids": [fid],\n            "edge_types": [],\n            "hop_count": 0,\n            "activation_contribution": act,\n        }\n        for fid, act in current.items()\n    }\n    graph_best_path: Dict[str, Dict[str, Any]] = {}\n    graph_exclusion_codes: set[str] = set()\n\n    for _hop in range(cfg.graph_walk_hops):\n        nxt: Dict[str, float] = {}\n        nxt_best_path: Dict[str, Dict[str, Any]] = {}\n''',
    )
    replace_once(
        "core/pipeline.py",
        '''                    targets.append((node, weight))\n            total_weight = sum(weight for _, weight in targets)\n            if total_weight <= 0.0:\n                continue\n            for node, weight in targets:\n                nid = node["fact_id"]\n                if nid in seeds:\n                    continue\n                share = act * cfg.graph_walk_decay * (weight / total_weight)\n                nxt[nid] = nxt.get(nid, 0.0) + share\n                node_cache[nid] = node\n''',
        '''                    targets.append((node, weight, rel_type))\n            total_weight = sum(weight for _, weight, _ in targets)\n            if total_weight <= 0.0:\n                continue\n            for node, weight, rel_type in targets:\n                nid = node["fact_id"]\n                if nid in seeds:\n                    continue\n                share = act * cfg.graph_walk_decay * (weight / total_weight)\n                nxt[nid] = nxt.get(nid, 0.0) + share\n                node_cache[nid] = node\n                parent_path = best_path.get(fid)\n                if parent_path is not None:\n                    candidate_path = {\n                        "seed_fact_id": parent_path["seed_fact_id"],\n                        "fact_ids": [*parent_path["fact_ids"], nid],\n                        "edge_types": [*parent_path["edge_types"], rel_type],\n                        "hop_count": parent_path["hop_count"] + 1,\n                        "activation_contribution": share,\n                    }\n                    previous = nxt_best_path.get(nid)\n                    if (previous is None\n                            or share > previous["activation_contribution"]\n                            or (share == previous["activation_contribution"]\n                                and tuple(candidate_path["fact_ids"]) < tuple(previous["fact_ids"]))):\n                        nxt_best_path[nid] = candidate_path\n''',
    )
    replace_once(
        "core/pipeline.py",
        '''            if (is_new_candidate\n                    and len(graph_score) >= cfg.graph_walk_candidate_limit):\n                continue\n            graph_score[nid] = graph_score.get(nid, 0.0) + val\n            bounded_next[nid] = val\n            if len(bounded_next) >= cfg.graph_walk_frontier_limit:\n                break\n        if not bounded_next:\n            break\n        current = bounded_next\n\n    for nid, score in graph_score.items():\n        graph_items.append(_from_node(node_cache[nid], score, "graph"))\n\n    # Fuse ranked candidate lists with RRF (ordering only — no truth/confidence change).\n''',
        '''            if (is_new_candidate\n                    and len(graph_score) >= cfg.graph_walk_candidate_limit):\n                graph_exclusion_codes.add("GRAPH_CANDIDATE_LIMIT_REACHED")\n                continue\n            graph_score[nid] = graph_score.get(nid, 0.0) + val\n            bounded_next[nid] = val\n            path = nxt_best_path.get(nid)\n            if path is not None:\n                previous = graph_best_path.get(nid)\n                if (previous is None\n                        or path["activation_contribution"] > previous["activation_contribution"]):\n                    graph_best_path[nid] = path\n            if len(bounded_next) >= cfg.graph_walk_frontier_limit:\n                if len(ranked_nxt) > len(bounded_next):\n                    graph_exclusion_codes.add("FRONTIER_LIMIT_REACHED")\n                break\n        if not bounded_next:\n            break\n        current = bounded_next\n        best_path = {nid: nxt_best_path[nid] for nid in bounded_next if nid in nxt_best_path}\n\n    for nid, score in graph_score.items():\n        item = _from_node(node_cache[nid], score, "graph")\n        path = graph_best_path.get(nid)\n        if path is not None:\n            item["_graph_explanation"] = {\n                "seed_fact_id": path["seed_fact_id"],\n                "contributor_paths": [{\n                    "fact_ids": path["fact_ids"],\n                    "edge_types": path["edge_types"],\n                    "hop_count": path["hop_count"],\n                    "activation_contribution": round(path["activation_contribution"], 6),\n                }],\n                "final_activation": round(score, 6),\n                "exclusion_reason_codes": sorted(graph_exclusion_codes),\n            }\n        graph_items.append(item)\n\n    # Fuse ranked candidate lists with RRF (ordering only — no truth/confidence change).\n''',
    )
    replace_once(
        "core/pipeline.py",
        '''    fused = (rankings[0] if len(rankings) == 1\n             else rrf_fuse(rankings, key=lambda x: x["id"]))\n    return fused[:k]\n''',
        '''    fused = (rankings[0] if len(rankings) == 1\n             else rrf_fuse(rankings, key=lambda x: x["id"]))\n\n    signals: Dict[str, set[str]] = {}\n    graph_explanations: Dict[str, Dict[str, Any]] = {}\n    for signal, items in (\n        ("vector", vector_items),\n        ("graph", graph_items),\n        ("seed", seed_items),\n    ):\n        for item in items:\n            signals.setdefault(item["id"], set()).add(signal)\n            if signal == "graph" and isinstance(item.get("_graph_explanation"), dict):\n                graph_explanations[item["id"]] = item["_graph_explanation"]\n\n    result: List[Dict[str, Any]] = []\n    for rank, item in enumerate(fused[:k], 1):\n        annotated = dict(item)\n        annotated["_retrieval_rank"] = rank\n        annotated["_retrieval_signals"] = sorted(signals.get(item["id"], {item.get("origin", "retrieval")}))\n        if item["id"] in graph_explanations:\n            annotated["_graph_explanation"] = graph_explanations[item["id"]]\n        result.append(annotated)\n    return result\n''',
    )


def patch_trace_tests() -> None:
    path = ROOT / "tests/test_trace.py"
    text = path.read_text(encoding="utf-8")
    text = text.replace('''    assert el["confidence"] == pytest.approx(0.42)\n''', '''    assert el["trace_version"] == 2\n    assert el["retrieval_score"] == pytest.approx(0.42)\n    assert "confidence" not in el\n    assert el["retrieval_rank"] == 1\n''')
    text += '''\n\ndef test_trace_v2_carries_bounded_retrieval_explanation():\n    trace = build_trace([{\n        "id": "f1",\n        "source": "s",\n        "_score": 0.7,\n        "_retrieval_rank": 2,\n        "_retrieval_signals": ["vector", "graph"],\n        "_active_embedder_id": "hashing-v1",\n        "_stored_embedder_id": "hashing-v1",\n        "_retrieval_config_id": "cfg",\n        "_projection_id": "canonical_read_only",\n        "_graph_explanation": {\n            "seed_fact_id": "seed",\n            "contributor_paths": [{\n                "fact_ids": ["seed", "f1"],\n                "edge_types": ["CO_OCCURRED"],\n                "hop_count": 1,\n                "activation_contribution": 0.2,\n            }],\n            "final_activation": 0.2,\n            "exclusion_reason_codes": [],\n        },\n    }])\n    entry = trace[0]\n    assert entry["retrieval_rank"] == 2\n    assert entry["retrieval_signals"] == ["vector", "graph"]\n    assert entry["active_embedder_id"] == "hashing-v1"\n    assert entry["retrieval_config_id"] == "cfg"\n    assert entry["graph_explanation"]["seed_fact_id"] == "seed"\n'''
    path.write_text(text, encoding="utf-8")


def write_wave2_tests() -> None:
    (ROOT / "tests/test_pre_freeze_wave2.py").write_text('''from __future__ import annotations\n\nfrom core import embedding, query_pipeline\nfrom core.l3_graph import MockL3Graph\n\n\ndef _validated_fact(fid: str, claim: str):\n    return {\n        "fact_id": fid, "claim": claim, "source": "src", "confidence": 1.0,\n        "epistemic_state": "Validated", "truth_status": "VERIFIED",\n        "claim_type": "WORLD_FACT", "source_status": "EXTERNAL",\n        "restricted": False,\n    }\n\n\ndef test_grant_profile_rejects_auto_embedder(monkeypatch):\n    graph = MockL3Graph()\n    graph.merge_fact(_validated_fact("f1", "alpha beta"))\n    monkeypatch.setattr(query_pipeline, "get_l3_graph", lambda: graph)\n    monkeypatch.setenv("VELANTRIM_RELEASE_PROFILE", "grant")\n    monkeypatch.setenv("VELANTRIM_EMBEDDER", "auto")\n    result = query_pipeline.search_result("alpha")\n    assert result["results"] == []\n    assert result["reason_code"] == "grant_profile_requires_pinned_embedder"\n\n\ndef test_embedder_mismatch_uses_labelled_bounded_lexical_fallback(monkeypatch):\n    graph = MockL3Graph()\n    monkeypatch.setenv("VELANTRIM_EMBEDDER", "hashing")\n    embedding.reset_embedder()\n    graph.merge_fact(_validated_fact("f1", "alpha beta"))\n    graph.set_embedder_fingerprint("different-space")\n    monkeypatch.setattr(query_pipeline, "get_l3_graph", lambda: graph)\n    result = query_pipeline.search_result("alpha")\n    assert [row["fact_id"] for row in result["results"]] == ["f1"]\n    assert result["retrieval"]["mode"] == "bounded_legacy_lexical"\n    assert result["retrieval"]["reason_code"] == "embedder_mismatch_lexical_fallback"\n    assert result["retrieval"]["stored_embedder_id"] == "different-space"\n\n\ndef test_pipeline_retrieval_explanation_is_navigation_not_confidence(monkeypatch):\n    graph = MockL3Graph()\n    monkeypatch.setenv("VELANTRIM_EMBEDDER", "hashing")\n    embedding.reset_embedder()\n    graph.merge_fact(_validated_fact("seed", "alpha seed"))\n    graph.merge_fact(_validated_fact("neighbor", "distant memory"))\n    graph.add_edge("seed", "CO_OCCURRED", "neighbor")\n    monkeypatch.setattr(query_pipeline, "get_l3_graph", lambda: graph)\n    monkeypatch.setattr("core.pipeline.get_l3_graph", lambda: graph)\n    graph.set_embedder_fingerprint(embedding.get_embedder().id)\n\n    result = query_pipeline.query("alpha")\n    assert result["trace"]\n    for entry in result["trace"]:\n        assert entry["trace_version"] == 2\n        assert "retrieval_score" in entry\n        assert "confidence" not in entry\n''', encoding="utf-8")


def main() -> None:
    patch_query_pipeline()
    patch_trace()
    patch_pipeline_explanation()
    patch_trace_tests()
    write_wave2_tests()


if __name__ == "__main__":
    main()
